export const SESSION_CONSTANTS = {
  INACTIVITY_TIMEOUT_MS: 1800000,
  TOKEN_REFRESH_INTERVAL_MS: 1200000,
  TOKEN_REFRESH_ENDPOINT: "/api/v2/auth/refresh",
  LOGOUT_ENDPOINT: "/api/v2/auth/logout",
  MIN_REFRESH_INTERVAL: 500000,
};
