export const SESSION_CONSTANTS = {
  INACTIVITY_TIMEOUT_MS: 180000,
  TOKEN_REFRESH_INTERVAL_MS: 120000,
  TOKEN_REFRESH_ENDPOINT: "/api/v2/auth/refresh",
  LOGOUT_ENDPOINT: "/api/v2/auth/logout",
  MIN_REFRESH_INTERVAL: 5000,
};
